Controllers/WeblistController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace PasswordManager.Controllers
{
    public class WeblistController : Controller
    {
        private readonly ILogger<WeblistController> _logger;
        private readonly ApplicationDbContext _db;

        public WeblistController(ILogger<WeblistController> logger, ApplicationDbContext db)
        {
            _logger = logger;
            _db = db;
        }

        public async Task<IActionResult> Add(Guid id)
        {
            var user = await _db.Users.FirstOrDefaultAsync(x => x.Id == id);
            if (user == null)
            {
                return NotFound();
            }
            ViewBag.UserId = user.Id;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(WebList web)
        {
                web.Id = Guid.NewGuid();
                await _db.WebLists.AddAsync(web);
                await _db.SaveChangesAsync();
                return RedirectToAction("Detail", "Home", new { id = web.UserId });

        }

        public async Task<IActionResult> Edit(Guid id)
        {
            var web = await _db.WebLists.FirstOrDefaultAsync(x => x.Id == id);
            return View(web);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id, Name, Title,Password,UserId")] WebList web)
        {
            var webToUpdate = _db.WebLists.FirstOrDefault(x => x.Id == web.Id);
            if (webToUpdate == null)
            {
                return NotFound();
            }
            webToUpdate.Id = web.Id;
            webToUpdate.Name = web.Name;
            webToUpdate.Title = web.Title;
            webToUpdate.Password = web.Password;

            _db.WebLists.Update(webToUpdate);
            await _db.SaveChangesAsync();
            return RedirectToAction("Detail", "Home", new { id = web.UserId });

        }

        public async Task<IActionResult> Delete(Guid id)
        {
            var web = await _db.WebLists.FirstOrDefaultAsync(x=>x.Id == id);
            if (web == null)
            {
                return NotFound();
            }
            return View(web);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(WebList web)
        {
            var userId = web.UserId;
            _db.WebLists.Remove(web);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }
        public async Task<IActionResult> Detail(Guid id)
        {
            var web = await _db.WebLists.Include(x => x.AppUser).FirstOrDefaultAsync(x => x.Id == id);
            if (web == null)
            {
                return NotFound();
            }

            return View(web);
        }
    }
}

Views/Weblist/Add.cshtml
@model WebList

@{
  ViewData["Title"] = "Create new password";
}
    <div class="container h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-lg-12 col-xl-11">
                <div class="card text-black" style="border-radius: 25px;">
                    <div class="card-body p-md-5">
                        <div class="row justify-content-center">
                            <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
                                <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">New Password</p>
                                <form asp-action="Add" asp-controller="Weblist" method="post" class="mx-1 mx-md-4">
                                    <input type="hidden" asp-for="Id">
                                    <div class="mb-4 d-flex align-items-center">
                                        <i class="bi bi-alphabet-uppercase me-3"></i>
                                        <input asp-for="Name" type="text" class="form-control" placeholder="Title" />
                                    </div>
                                    <div class="mb-4 d-flex align-items-center">
                                        <i class="bi bi-globe me-3"></i>
                                        <input asp-for="Title" type="text" class="form-control" placeholder="Url/Phone" />
                                    </div>
                                    <div class="mb-4 d-flex align-items-center">
                                        <i class="bi bi-lock-fill me-3"></i>
                                        <input asp-for="Password" type="password" class="form-control" placeholder="Password" />
                                    </div>
                                    <div class="mb-4 d-flex align-items-center">
                                        <i class="bi bi-journal-text me-3"></i>
                                        <textarea asp-for="Note" class="form-control" placeholder="Add some note..." rows="3"></textarea>
                                    </div>
                                    <input type="hidden" asp-for="UserId" value="@ViewBag.UserId">
                                    <div class="d-flex justify-content-center mb-3">
                                        <button type="submit" class="btn btn-outline-primary btn-lg">Create</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

Views/Weblist/Delete.cshtml
@model WebList
@* @{
  ViewData["Title"] = "Delete";
}
<h2 class="text-danger">Are you sure to delete password for @Model.Name</h2>
<form asp-action="Delete" method="post">
    <input type="hidden" asp-for="@Model.Id" />
    <button type="submit" class="btn btn-outline-danger">Delete</button>
    <a href="/home/index" class="btn btn-outline-success">Cancel</a>
</form>
 *@

@{
  ViewData["Title"] = "Delete password";
}
    <div class="container h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-lg-12 col-xl-11">
                <div class="card text-black" style="border-radius: 25px;">
                    <div class="card-body p-md-5">
                        <div class="row justify-content-center">
                            <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
                                <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Are you sure to delete password for @Model.Name</p>
                                <form asp-action="Delete" asp-controller="Weblist" method="post" class="mx-1 mx-md-4">
                                    <input type="hidden" asp-for="Id">
                                    <div class="d-flex justify-content-center mb-3">
                                        <button type="submit" class="btn btn-outline-danger" style="margin-right: 3px;">Delete</button>
                                        <a href="/home/index" class="btn btn-outline-success">Cancel</a>
                                    </div>
                                    
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

Views/Weblist/Detail.cshtml
@model WebList
<div class="d-flex justify-content-center align-items-center ">
<div class="p-3 rounded shadow" style="width: 500px; height:50vh;">
        <div class="header">
            <h1 class="mb-3 text-center fs-5 text-dark font-monospace">@Model.Name</h1>
        </div>
        <div class="mb-3">
            <div class="mb-3">
                <label asp-for="Title">URL/Phone</label>
                <div class="input-group">
                    <input type="text" id="username" value="@Model.Title" readonly>
                    <button class="copy-btn" onclick="copyToClipboard('username')">📋</button>
                </div>
            </div>
            <div class="mb-3">
                <label for="password">Password</label>
                <div class="input-group">
                    <input type="password" id="password" value="@Model.Password" readonly>
                    <button class="view-btn" onclick="togglePasswordVisibility()">👁️</button>
                </div>
            </div>
            <div class="mb-3">
                <label asp-for="Note"></label>
                <div class="input-group">
                    <input type="text" value="@Model.Note" readonly>
                </div>
            </div>
        </div>
        <div class="footer">

            <a asp-controller="Weblist" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-outline-primary">Edit</a>
            <a asp-controller="Weblist" asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-outline-danger">Delete</a>
        </div>
    </div>
</div>

    <script>
        function togglePasswordVisibility() {
            var passwordInput = document.getElementById('password');
            var viewButton = document.querySelector('.view-btn');
            if (passwordInput.type === 'password') {
                passwordInput.type = 'text';
                viewButton.textContent = '🙈';
            } else {
                passwordInput.type = 'password';
                viewButton.textContent = '👁️';
            }
        }

        function copyToClipboard(elementId) {
            var copyText = document.getElementById(elementId);
            copyText.select();
            document.execCommand("copy");
        }
    </script>

<style>
.input-group input {
     background-color: rgb(201, 201, 201);
    flex: 1;
    padding: 10px;
    border: none;
    border-radius: 5px 0 0 5px;
}

.input-group button {
    padding: 10px;
    border: none;
    border-radius: 0 5px 5px 0;
    cursor: pointer;
}

.input-group button:hover {
    background-color: #555555;
}

.field input[readonly] {
    background-color: #333333;
}




</style>

Views/Weblist/Edit.cshtml
@model WebList

@{
  ViewData["Title"] = "Edit password";
}
    <div class="container h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-lg-12 col-xl-11">
                <div class="card text-black" style="border-radius: 25px;">
                    <div class="card-body p-md-5">
                        <div class="row justify-content-center">
                            <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
                                <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Edit Password</p>
                                <form asp-action="Edit" asp-controller="Weblist" method="post" class="mx-1 mx-md-4">
                                    <input type="hidden" asp-for="Id">
                                    <div class="mb-4 d-flex align-items-center">
                                        <i class="bi bi-alphabet-uppercase me-3"></i>
                                        <input asp-for="Name" type="text" class="form-control" placeholder="Title" />
                                    </div>
                                    <div class="mb-4 d-flex align-items-center">
                                        <i class="bi bi-globe me-3"></i>
                                        <input asp-for="Title" type="text" class="form-control" placeholder="Url/Phone" />
                                    </div>
                                    <div class="mb-4 d-flex align-items-center">
                                        <i class="bi bi-lock-fill me-3"></i>
                                        <input asp-for="Password" type="text" class="form-control" placeholder="Password" />
                                    </div>
                                    <div class="mb-4 d-flex align-items-center">
                                        <i class="bi bi-journal-text me-3"></i>
                                        <textarea asp-for="Note" class="form-control" placeholder="Add some note..." rows="3"></textarea>
                                    </div>
                                    <input type="hidden" asp-for="UserId">
                                    <div class="d-flex justify-content-center mb-3">
                                        <button type="submit" class="btn btn-outline-primary btn-lg">Update</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>